// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type Edge = { id: string; source: string; target: string }

export type Graph = { nodes: Node[]; edges: Edge[] }

export type Node = { id: string; position: Point; data: NodeData; type: string }

export type NodeData = { label: string }

export type Point = { x: number; y: number }

const ARGS_MAP = { '':'{"hello_world":["name"],"load_graph":["filename"],"save_graph":["graph","filename"]}' }
export type Router = { "": {hello_world: (name: string) => Promise<string>, 
load_graph: (filename: string) => Promise<Graph>, 
save_graph: (graph: Graph, filename: string) => Promise<string>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
