version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ "
      include: "scope"

  - package-ecosystem: "cargo"
    directory: "/core"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ "
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ "
      include: "scope"
