- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"

- name: "rust"
  color: "dea584"
  description: "Related to Rust/backend code"

- name: "frontend"
  color: "ff6f00"
  description: "Related to frontend/UI code"

- name: "tauri"
  color: "ffc131"
  description: "Related to Tauri integration"

- name: "ci/cd"
  color: "ededed"
  description: "Related to CI/CD workflows"

- name: "tests"
  color: "c2e0c6"
  description: "Related to testing"

- name: "breaking change"
  color: "b60205"
  description: "Introduces a breaking change"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"
