/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Node {
  data: NodeData;
  id: string;
  position: Position;
  selected: boolean;
  type: string;
  [k: string]: unknown;
}
export interface NodeData {
  label: string;
  [k: string]: unknown;
}
export interface Position {
  x: number;
  y: number;
  [k: string]: unknown;
}
