/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Level = "success" | "error" | "warning" | "information";

export interface Notification {
  body?: string | null;
  call_to_action?: string | null;
  call_to_action_secondary?: string | null;
  level: Level;
  title: string;
  [k: string]: unknown;
}
