// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type ArgumentType = "string" | "number" | "boolean" | "enum"

export type Brick = { id: string; label: string; description: string; keywords: string[]; category: string; arguments: BrickArgument[]; inputs: BrickInput[]; outputs: BrickOutput[]; execution_inputs: BrickExecutionInput[]; execution_outputs: BrickExecutionOutput[] }

export type BrickArgument = { id: string; label: string; type: ArgumentType; enumOptions: string[] | null; defaultValue: string | null }

export type BrickExecutionInput = { id: string; label: string }

export type BrickExecutionOutput = { id: string; label: string }

export type BrickInput = { id: string; label: string; type: ConnectionType; defaultValue: string | null }

export type BrickOutput = { id: string; label: string; type: ConnectionType }

export type BrickOutputValue = { id: string; value: string }

export type ConnectionType = "flow" | "string" | "number" | "boolean" | "enum"

export type Edge = { id: string; source: string; target: string; sourceHandle: string; targetHandle: string }

export type ExecutionMode = "Normal" | "Stepped"

export type ExecutionPhase = "Waiting" | "Queued" | "Running" | "Completed" | "Errored"

/**
 * Result of executing the entire graph
 */
export type ExecutionResult = { total_nodes: number; success: boolean; error: string | null }

export type ExecutionStateUpdate = { node_id: string; state: NodeExecutionState; execution_mode: ExecutionMode }

export type Graph = { nodes: Node[]; edges: Edge[] }

export type Node = { id: string; position: Point; data: NodeData; type: string }

export type NodeData = { brickId: string; brick: Brick | null; arguments: Partial<{ [key in string]: string }>; defaults: Partial<{ [key in string]: string }> }

export type NodeExecutionState = { phase: ExecutionPhase; errorMessage: string | null; elapsedMs: number; outputs: BrickOutputValue[] | null }

export type Point = { x: number; y: number }

const ARGS_MAP = { '':'{"execute_graph":["graph","mode"],"get_brick":["brick_id"],"get_bricks":[],"graph_updated":["graph"],"insert_node":["graph_path","brick_id","position"],"load_graph":["filename"],"node_execution_updated":["update"],"save_graph":["graph","filename"]}' }
export type Router = { "": {execute_graph: (graph: Graph, mode: ExecutionMode) => Promise<ExecutionResult>, 
get_brick: (brickId: string) => Promise<Brick | null>, 
get_bricks: () => Promise<Brick[]>, 
graph_updated: (graph: Graph) => Promise<void>, 
insert_node: (graphPath: string, brickId: string, position: Point) => Promise<Graph>, 
load_graph: (filename: string) => Promise<Graph>, 
node_execution_updated: (update: ExecutionStateUpdate) => Promise<void>, 
save_graph: (graph: Graph, filename: string) => Promise<string>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
