name: create release
on:
    milestone:
        types: [closed]

jobs:
    changelog:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Generate release notes
              uses: Decathlon/release-notes-generator-action@v3.1.6
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  USE_MILESTONE_TITLE: "true"
                  FILENAME: "CHANGELOG"

            - name: Push changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "Update CHANGELOG.md"

    release:
        needs: changelog
        permissions: write-all
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 19
                  cache: "yarn"

            - name: Setup Yarn
              run: npm install --global yarn

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.0.x

            - name: Install Node dependencies
              run: yarn install

            - name: Tag version
              run: yarn run version ${{ github.event.milestone.title }}

            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                  workspaces: "./src-tauri -> target"

            - name: Restore C# dependencies
              run: dotnet restore src-csharp

            - name: Read changelog
              id: notes
              uses: jaywcjlove/github-action-read-file@main
              with:
                  path: CHANGELOG.md

            - name: Build application
              uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
                  releaseName: Vla ${{ github.event.milestone.title }}
                  releaseBody: ${{ steps.notes.outputs.content }}
                  prerelease: false
                  includeUpdaterJson: true
