permissions:
    contents: write

name: create release
on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codebase
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "yarn"

            - name: Setup extension abstraction dependencies
              run: yarn install --frozen-lockfile
              working-directory: ./src/extensions/abstractions

            - name: Publish extension abstraction
              run: npm publish --access public
              working-directory: ./src/extensions/abstractions

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  prerelease: ${{ contains(github.ref, '-next') }}
