name: create release
on:
    push:
        tags:
            - "*"

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 19

            - name: Setup Yarn
              run: npm install --global yarn

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.0.x

            - name: Install Node dependencies
              run: yarn install

            - name: Tag version
              run: yarn run version ${{ github.ref }}

            - name: Apply cache
              uses: Swatinem/rust-cache@v2

            - name: Restore C# dependencies
              run: dotnet restore src-csharp

            - name: Build application
              uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
                  releaseName: "Vla v__VERSION__"
                  releaseBody: "See the assets to download this version and install."
                  releaseDraft: true
                  prerelease: false
